### ISSUE TITLE
[Template] Romance

### ISSUE THREAD

**Issue by TorstenDittmann** [TorstenDittmann/omnia-ebook-generator#4]
To add more variety, I would like to have a **romance** ❤️ themed template. 

Everything to know about contributing to this repository can be found [here](https://github.com/TorstenDittmann/omnia-ebook-generator/blob/master/CONTRIBUTING.md#contributing).

You can let your creativity run wild, it just has to fit the theme. For inspiration just look into your bookshelf 😉 

For further questions you can simply answer here 🙂

**Comment by alejandra-gonzalez** [comment]
Hello, may I work on this?

**Comment by TorstenDittmann** [comment]
Of course!

Feel free to ask if you have any questions 👍

**Comment by TorstenDittmann** [comment]
@allcontributors add @alejandra-gonzalez for code
